CdLeng/concertify

- app/models/artist.rb
- app/models/artist_genre.rb
- app/models/concert.rb
- app/models/followed_artist.rb
- app/models/genre.rb
- app/models/saved_concert.rb
- db/migrate/20230306182702_create_genres.rb
- db/migrate/20230306182804_create_artists.rb
- db/migrate/20230306182905_create_concerts.rb
- db/migrate/20230306183938_create_artist_genres.rb
- db/migrate/20230306184118_create_saved_concerts.rb
- db/migrate/20230306184214_create_followed_artists.rb
- db/migrate/20230306184848_add_arists_id_to_concerts.rb
- db/migrate/20230306190225_set_default_attendedin_saved_concerts.rb
- db/schema.rb
- test/models/artist_genre_test.rb
- test/models/artist_test.rb
- test/models/concert_test.rb
- test/models/followed_artist_test.rb
- test/models/genre_test.rb
- test/models/saved_concert_test.rb
created all models in this branch
1. creating artists, concerts and genres model
2. added the followed_artiss, artist_genres and saved_concerts models. I put the attended column in saved_concerts as boolean
3. added the artists_id to the concerts table
> Models creation

- app/controllers/genres_controller.rb
- app/controllers/saved_concerts_controller.rb
- app/models/genre.rb
- test/controllers/genres_controller_test.rb
- test/controllers/saved_concerts_controller_test.rb
added a uniqueness validation to the name column in genres
> Saved concerts and genres controllers

- app/models/artist.rb
- app/models/concert.rb
- app/models/genre.rb
- app/models/user.rb
Please double check this as im not too sure
> added the has_many and belongs_to to the models.

- app/models/artist.rb
- app/models/artist_genre.rb
- app/models/concert.rb
- app/models/followed_artist.rb
- app/models/saved_concert.rb
- app/models/user.rb
- db/migrate/20230307164956_change_artist_description_to_text.rb
- db/migrate/20230307165345_change_concert_description_to_text.rb
- db/migrate/20230307203026_change_attented_for_concerts.rb
- db/schema.rb
- Added validation for ArtistGenre, so that you can't add the same genre for the same artist more than once
- Changed the description data type for artist and concert to text instead of string (allows more characters)
- Added validation for descriptrion length for artist and concert model
- **Added `has_one` association for followed_artist and saved_concert, not very sure about this one. It's not a has many because an artist has only 1 followed artist.**
> Added validations

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/devise/registrations/new.html.erb
- app/views/shared/_navbar.html.erb
- config/environments/development.rb
- config/storage.yml
- db/migrate/20230310201712_create_active_storage_tables.active_storage.rb
- db/schema.rb
- test/controllers/users_controller_test.rb
- Added profile pic to user model
- Profile pic is stored in Cloudinary
- Added ActiveStorage
- Permitted fields name and address in the user model devise (you couldn't register with name'/adress without) by changing the application controller
- Profile pic is showed in the nav bar, if empty there is a default pic showed
> Profile pic

- app/controllers/concerts_controller.rb
- app/controllers/saved_concerts_controller.rb
- app/policies/concert_policy.rb
- app/views/concerts/show.html.erb
- config/routes.rb
(Merge this AFTER the concerts#index)
> created action + view for each concert (concerts#show)

- app/assets/stylesheets/components/_concert_card_one.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_layout.scss
- app/assets/stylesheets/components/_search.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/config/_fonts.scss
- app/assets/stylesheets/pages/_concert_show.scss
- app/views/concerts/index.html.erb
- app/views/shared/_concert_card_one.html.erb
- Added some of the front end for the concerts index page
- Created one type of card component
- Added some colors variables
- Added the font family that we used in InstrumentsBnb to the headers
> added style for the concerts index, and created the card-component

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/pages/_artists_index.scss
- app/controllers/artists_controller.rb
- app/policies/artist_policy.rb
- app/views/artists/index.html.erb
- app/views/artists/show.html.erb
- config/routes.rb
- db/migrate/20230317202031_add_image_url_to_artists.rb
- db/schema.rb
- Artist index returns Spotify artists for a search query
- Artist is saved in DB when it is clicked on the index
- Genres are assigned to artist
- Image_url is saved in artist (added image_url as column to artist model)
- Added create actions in route for Artist and Concert
- Changed artist show page so that the artist content is shown (image, genres, description)
> Artists api

- app/views/pages/home.html.erb
also made it so that the welcome message is to the first name and moved down the checkout these concerts message
> Change welcome message to name

- app/controllers/artists_controller.rb
- app/policies/artist_policy.rb
users who are not logged in, can now search for an artist and click on their profile
this includes "new" artists that are not in the db
> allow not logged in users to search for artists and view artists profile

- app/views/concerts/show.html.erb
Also changed the wording to be Price from
> changed the price to always round down, and show as integer. 

- app/assets/stylesheets/pages/_artists_index.scss
- app/views/followed_artists/index.html.erb
Added image URL to show the nice image
also shortened the description
> Followed artist front end

- app/assets/stylesheets/pages/_concerts_index.scss
> added pading on the grid and opacity change on hover

- Gemfile.lock
- app/views/artists/show.html.erb
- app/views/concerts/show.html.erb
- app/views/saved_concerts/index.html.erb
and also the about text in the concert show is a bit longer now
> Cleaned description on artist page to be longer, but stop at the <a

- app/assets/stylesheets/pages/_concerts_index.scss
- app/javascript/controllers/map_controller.js
- app/views/concerts/index.html.erb
> put the map bellow the grid + changed color to lighter gray

- app/assets/stylesheets/components/_content.scss
> Removed white space between content and footer by adding bg color to content div

- Gemfile.lock
- app/assets/stylesheets/pages/_concert_show.scss
- app/views/concerts/show.html.erb
> added the concert title, below the artist title.

- app/controllers/artists_controller.rb
To prevent too many requests in the pitch, in this way we are safe when we go to artist show page where concerts alreadty exist
> Ony fetch concerts from ticketmaster if artist has no concerts yet

- app/assets/stylesheets/pages/_artists_index.scss
- app/controllers/followed_artists_controller.rb
- app/views/followed_artists/index.html.erb
https://i.imgur.com/8YImvcE.png
> Added option to unfollow artists on index

- app/assets/stylesheets/components/_concert_card_one.scss
- app/controllers/saved_concerts_controller.rb
- app/views/saved_concerts/index.html.erb
https://i.imgur.com/FNCMzJ0.png
> Added unsave option to saved concerts index

- app/assets/stylesheets/pages/_artists_index.scss
- app/views/artists/index.html.erb
- app/views/artists/show.html.erb
- app/views/concerts/index.html.erb
- app/views/concerts/show.html.erb
- app/views/followed_artists/index.html.erb
- app/views/saved_concerts/index.html.erb
- db/schema.rb
Adjusted styling for go back buttons so they all have the same styling.
> adjusted styling for buttons

- app/assets/stylesheets/pages/_artist_show.scss
added transition to hover effect for artist concert card
> added transition to hover effect for artist card
